name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9
        uses: docker/build-push-action@v4.2.1
        with:
          push: true # optional, default is false
          tags: ghcr.io/loredous/unifios-dns-manager:latest # optional
