on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create release assets

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package Code
        run: |
          zip -r dns-manager-backend release.zip
          zip -r dns-manager-frontend release.zip
          zip unifios_dns_manager_start.sh release.zip
      - uses: Shopify/upload-to-release@v1.0.1
        with:
          name: update_bundle
          path: release.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
