on:
  release:
    types: [published]

name: Create release assets

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package Code and upload
        run: |
          zip -r release.zip dns-manager-backend
          zip -r release.zip dns-manager-frontend
          zip release.zip unifios_dns_manager_start.sh
          echo $TAG
          gh release upload ${GITHUB_REF_NAME} release.zip 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
